name: benchmark
on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

jobs:
  verify_preference:
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["4.0", "jruby-10.0", "truffleruby"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - run: BENCHMARK_ARGS=--verify-preference bundle exec rake benchmark
