name: ci
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        ruby: ["3.2", "3.3", "3.4", "jruby-10"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake test
